name       : libtrace
version    : 4.0.5
release    : 3
source     :
    - https://research.wand.net.nz/software/libtrace/libtrace-4.0.5.tar.bz2 : ee6d21e3e341e4b4ec6fa69f85deda3df930659177768baa7e7bd4db33e4248a
license    : GPL-3.0-or-later
component  : programming.library
summary    : libtrace is a library for trace processing
description: |
    libtrace is a library for trace processing. It supports multiple
    input methods, including device capture, raw and gz-compressed trace,
    and sockets; and multiple input formats, including pcap and DAG.
builddeps  :
    - pkgconfig(ncursesw)
    - pkgconfig(openssl)
    - libpcap-devel
    - libwandio-devel
    - llvm-devel
    - lzo-devel
setup      : |
    %configure \
        --disable-static \
        --with-llvm \
        --with-ncurses
build      : |
    %make
install    : |
    %make_install
